spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alurafake
    username: postgres
    password: postgres
  jpa:
    hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false