CREATE TABLE TaskOption (
    id BIGINT NOT NULL AUTO_INCREMENT,
    option_name VARCHAR(255) NOT NULL,
    isCorrect BOOLEAN NOT NULL,
    task_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_Task FOREIGN KEY (task_id) REFERENCES Task(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;