name: deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: github
      POSTGRES_DB: alurafake
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: alurafake
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          for i in {1..30}; do
            nc -z localhost 5432 && echo "PostgreSQL is up!" && break
            echo "Waiting..."
            sleep 2
          done

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/alura_fake-1.0-SNAPSHOT.jar alura_fake-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@v4
        with:
          name: alura_fake
          path: alura_fake-${{ github.sha }}.jar

  fake-deploy:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@v4
        with:
          name: alura_fake

      - name: Move artifact to root
        run: mv alura_fake/alura_fake-*.jar .

      - name: Fake deploy
        run: |
          echo "Listando artefato para deploy:"
          ls alura_fake-*.jar