name: jobs-tests

on:
  push:
    branches-ignore:
      - main

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven  # opcional, habilita cache do Maven

      - name: Run all tests
        run: mvn clean install