name: jobs-tests

on:
  push:
    branches-ignore:
      - main

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: github
      POSTGRES_DB: alurafake
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: alurafake
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          for i in {1..30}; do
            nc -z localhost 5432 && echo "PostgreSQL is up!" && break
            echo "Waiting..."
            sleep 2
          done

      - name: Run tests with Maven
        run: mvn clean verify